
#' Converts the PEAKS BED12 format to a usable GRanges BED6 format for downstream analysis
#'
#' @param PEAKS A data frame containing the following columns, and potentially extras, usually found in a BED12 file, base 0 system
#' @param GENEINFO A list of gene attributes generated by the get.gene.anno function
#'
#' @return a GenomicRanges object in BED6 format containing only peaks assigned to a gene with an extra column for the peak index from where it was extracted and a sample id
.retrieve.peaks.as.granges = function(PEAKS, GENEINFO){

  PEAKS = PEAKS[PEAKS$name == GENEINFO$gene,]

  # Verify that all the columns have the
  BED6 = data.frame(stringsAsFactors = F)
  for(i in 1:nrow(PEAKS)){
    tmp = data.frame(
      "chr" = PEAKS$chr[i],
      "start" = PEAKS$start[i] + strtoi(strsplit(PEAKS$blockStarts[i], split = ",")[[1]]),
      "end" = PEAKS$start[i] + strtoi(strsplit(PEAKS$blockStarts[i], split = ",")[[1]]) + strtoi(strsplit(PEAKS$blockSizes[i], split = ",")[[1]]),
      "name" = PEAKS$name[i],
      "score" = PEAKS$score[i],
      "strand" = PEAKS$strand[i],
      "peak" = i,
      "sample" = PEAKS$sample[i],
      stringsAsFactors = F
    )
    BED6 = rbind(BED6, tmp)
  }

  makeGRangesFromDataFrame(BED6, keep.extra.columns = T)
}
